// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"cloud.google.com/go/bigquery"
	"context"
	"github.com/googleapis/google-cloud-go-testing/bigquery/bqiface"
	"github.com/pkg/errors"
	"github.com/rerost/bq-table-validator/domain/bqquery"
	"github.com/rerost/bq-table-validator/domain/tablemock"
	"github.com/rerost/bq-table-validator/domain/validator"
	"github.com/spf13/cobra"
	"go.uber.org/zap"
	"time"
)

// Injectors from wire.go:

func InitializeCmd(ctx context.Context, cfg Config) (*cobra.Command, error) {
	client, err := NewBQClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	middleware := NewBQMiddleware(client)
	time := NewTime()
	tableMock := tablemock.NewTableMock(time)
	validatorValidator := validator.NewValidator(middleware, tableMock)
	command := NewCmdRoot(ctx, validatorValidator)
	return command, nil
}

// wire.go:

func NewBQClient(ctx context.Context, cfg Config) (bqiface.Client, error) {
	zap.L().Debug("Create BQ Client", zap.String("ProjectID", cfg.ProjectID))
	bqClient, err := bigquery.NewClient(ctx, cfg.ProjectID)
	if err != nil {
		return nil, errors.WithStack(err)
	}

	return bqiface.AdaptClient(bqClient), nil
}

func NewBQMiddleware(bqClient bqiface.Client) validator.Middleware {
	return bqquery.NewBQQuery(bqClient)
}

func NewTime() time.Time {
	return time.Now()
}
